title: The Republic of Agora
description: UNITE THE PUBLIC ♢ VOL.47 © MMXXIV
baseurl: "/pen/0x2f" # subpath of your site, e.g. /blog
url: "https://agora0.github.io" # hostname & protocol, e.g. http://example.com
google_analytics: 'UA-166928354-2' # agorahub-pen0
gh_team: orgs/agorahub/teams/pen
gh_repo: agorahub/pen0

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - octopress-paginate

excerpt_separator: <!--more-->
collections_dir: _collections
collections:
  heros:
    output: true
  columns:
    output: true
  hkers:
    output: true

# Social media
github:   agorahub
reddit: u/agoradao
twitter:  agoradao
telegram: agorahub
#linkedin: linkedin
#facebook: facebook
